[theme]
primaryColor = "#6CA0DC"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#181b20"
textColor = "#fafafa"
font = "Poppins, sans-serif"

[[theme.fontFaces]]
family = "Poppins"
url = "url('https://fonts.gstatic.com/s/poppins/v21/pxiEyp8kv8JHgFVrFJA.woff2')"
